include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  rules:
    public_member_api_docs: true
    avoid_print: true
    prefer_single_quotes: true
    require_trailing_commas: true
    cancel_subscriptions: true
    unnecessary_statements: true
    avoid_redundant_argument_values: true
    unnecessary_await_in_return: true
    await_only_futures: true
    unawaited_futures: true
